# Generated by Django 3.2.9 on 2022-08-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliced', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography_type',
            name='photography_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
