# Generated by Django 3.2.9 on 2022-08-05 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sliced', '0002_alter_photography_type_photography_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolia',
            name='coverImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image/portfolio/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolia',
            name='title',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
