# Generated by Django 3.2.9 on 2022-08-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliced', '0003_auto_20220805_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolia',
            name='coverImage',
            field=models.ImageField(upload_to='image/portfolio/cover/'),
        ),
        migrations.AlterField(
            model_name='portofolia',
            name='img1',
            field=models.ImageField(upload_to='image/portfolio/'),
        ),
        migrations.AlterField(
            model_name='portofolia',
            name='img2',
            field=models.ImageField(upload_to='image/portfolio/'),
        ),
        migrations.AlterField(
            model_name='portofolia',
            name='img3',
            field=models.ImageField(upload_to='image/portfolio/'),
        ),
        migrations.AlterField(
            model_name='portofolia',
            name='img4',
            field=models.ImageField(upload_to='image/portfolio/'),
        ),
        migrations.AlterField(
            model_name='portofolia',
            name='img5',
            field=models.ImageField(upload_to='image/portfolio/'),
        ),
    ]
