# Generated by Django 3.2.9 on 2022-08-06 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sliced', '0005_alter_portofolia_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='userId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='userId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='photography_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_id', to='sliced.portofolia'),
        ),
    ]
