# Generated by Django 3.2.9 on 2022-08-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliced', '0006_auto_20220806_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='commentTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
