# Generated by Django 3.2.9 on 2022-08-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliced', '0009_alter_booking_details_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
